apiVersion: v1
kind: Service
metadata:
  name: nfs-server   # The local domain name of the Service in the cluster
spec:
  ports:
  - protocol: TCP
    port: 2049
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nfs-server
subsets:
  - addresses:
      - ip: 192.168.66.40
    ports:
      - port: 2049