apiVersion: apps/v1
kind: Deployment
metadata:
# name by which the deployment will be identified and
# referred to by other resources
  name: numbers-web
spec:
  selector:
  # matchLabels is used to match the labels of the pods
    matchLabels:
      app: gonumbers-web
  template:
    metadata:
    # labels are used to identify the pods
      labels:
        app: gonumbers-web
    spec:
      containers:
        - name: web
          image: gonumbersweb4
          # imagePullPolicy is set to Never to indicate that
          # the image will not be pulled from a registry (local one)
          imagePullPolicy: Never
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
          env:
            - name: KIAMOL.SECTION
              value: "04.01"
      volumes:
        - name: config
          configMap:
            name: go-numbers-config-json    
