apiVersion: v1
kind: Service
metadata:
  name: numbers-web2-nodeport
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    app: lab-numbers-web
    version: v2
  type: NodePort