apiVersion: v1
kind: Service
metadata:
  name: numbers-web-nodeport
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30180
  selector:
    app: lab-numbers-web
    version: v1
  type: NodePort