apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    server {
        listen 1080;

        location /api {
            proxy_pass http://numbers-api/sixeyed/kiamol/master/ch03/numbers/rng;
        }

        location / {
            return 403;
        }
    }