apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    kiamol: ch07
spec:
  containers:
    - name: sleep
      image: kiamol/ch03-sleep
      command: ['sh', '-c', "cat /etc/ca-certificates.conf  > /config-out/appsettings.json"]
      volumeMounts:
        - name: config-dir
          mountPath: /config-out
  volumes:
    - name: config-dir
      emptyDir: {}