apiVersion: v1
kind: Pod
metadata:
  name: sleep
  labels:
    kiamol: ch07
spec:
  containers:
    - name: container1
      image: kiamol/ch03-sleep
    - name: container2
      image: kiamol/ch03-sleep
